### ISSUE TITLE
Gem don't compile with ruby-1.9.1 in Windows

### ISSUE THREAD

**Issue by atimin** [hparra/ruby-serialport#6]
C:/Ruby19/bin/ruby.exe extconf.rb
checking for OS... mingw
creating Makefile

make
gcc -I. -IC:/Ruby19/include/ruby-1.9.1/i386-mingw32 -I/C/Ruby19/include/ruby-1.9.1/ruby/backward -I/C/Ruby19/include/ruby-1.9.1 -Isrc   -O2 -g -Wall -Wno-parentheses  -DOS_MINGW -DRUBY_19  -o posix_serialport_impl.o -c src/posix_serialport_impl.c
gcc -I. -IC:/Ruby19/include/ruby-1.9.1/i386-mingw32 -I/C/Ruby19/include/ruby-1.9.1/ruby/backward -I/C/Ruby19/include/ruby-1.9.1 -Isrc   -O2 -g -Wall -Wno-parentheses  -DOS_MINGW -DRUBY_19  -o serialport.o -c src/serialport.c
gcc -I. -IC:/Ruby19/include/ruby-1.9.1/i386-mingw32 -I/C/Ruby19/include/ruby-1.9.1/ruby/backward -I/C/Ruby19/include/ruby-1.9.1 -Isrc   -O2 -g -Wall -Wno-parentheses  -DOS_MINGW -DRUBY_19  -o win_serialport_impl.o -c src/win_serialport_impl.c
src/win_serialport_impl.c: In function `get_handle_helper':
src/win_serialport_impl.c:38: error:`fptr' undeclared (first use in this function)
src/win_serialport_impl.c:38: error: (Each undeclared identifier is reported only once
src/win_serialport_impl.c:38: error: for each function it appears in.)
src/win_serialport_impl.c: In function `sp_create_impl':
src/win_serialport_impl.c:47: error:`fp' undeclared (first use in this function)
src/win_serialport_impl.c:78: error: structure has no member named `ptr'
src/win_serialport_impl.c: In function`get_line_signals_helper_impl':
src/win_serialport_impl.c:543: warning: passing arg 2 of `GetCommModemStatus' from incompatible pointer type
make: **\* [win_serialport_impl.o] Error 1

I'm using:
rubyinstaller-1.9.1-p243-rc1 with devkit devkit-3.4.5r3
OS: Windosws XP, Windows 7
